bracketSpacing: true
endOfLine: 'auto'
printWidth: 100
proseWrap: 'always'
singleQuote: true
tabWidth: 2
trailingComma: 'all'

overrides:
  - files: '*.sol'
    options:
      compiler: '0.8.17'
      singleQuote: false
      tabWidth: 4
      printWidth: 120
